services:
  postgres:
    image: postgres:16
    container_name: facturacion-postgres
    environment:
      POSTGRES_DB: facturacion_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
    ports:
      - "5433:5432"  # Change host port to 5433
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: